# Deploy to github pages

---
name: Deploy to GitHub Pages
on:
  push:
    branches:
      - main
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Upload site
              uses: actions/upload-pages-artifact@v3
              with:
                path: ./
    deploy:
        # Add a dependency to the build job
        needs: build
        # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
        permissions:
            contents: read
            pages: write
            id-token: write
        # Deploy to the github-pages environment
        environment:
          name: github-pages
          url: ${{ steps.deploy-to-github-pages.outputs.page_url }}
        # Specify runner + deployment step
        runs-on: ubuntu-latest
        continue-on-error: false
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Setup Node.js
              uses: actions/setup-node@v3
              with:
                node-version: '20'
            
            - name: Deploy to GitHub Pages
              id: deploy-to-github-pages 
              uses: actions/deploy-pages@v4

...